[package]
name = "cleanup_pix"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"

[profile.release]
opt-level = "z"  # Optimize for size.
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
panic = "abort"
